### ISSUE TITLE
No es posible crear dataset con un usuario de tipo *colaborador* 

### ISSUE THREAD

**Issue by JoseSalgado1024** [datosgobar/portal-andino-theme#100]
Cuando intentamos grabar un nuevo dataset utilizando un usuario _colaborador_, **automaticamente se cierra la session del usuario perdiendo toda la informacion del dataset que se estaba creando**.

Este error no ocurre al intentar crear datasets mediante con usuario **colaborador** a través de la **CKAN.API** _(VERSION == 3)_

**Comment by poligarcia** [comment]
Aparentemente el issue se puede reproducir cuando el usuario selecciona un "Tema específico" del portal andino:

![image](https://user-images.githubusercontent.com/1264073/34437096-2524e4f4-ec7a-11e7-804e-117d2b77b8c2.png)

**Comment by poligarcia** [comment]
Sucede lo mismo editando un dataset existente y seleccionando el tema específico.
