### ISSUE TITLE
Question Dashboard

### ISSUE THREAD

**Issue by bishalkc** [datosgobar/portal-andino-theme#101]
Hello, 

Does the theme support ckan-dashboard, I see the build (docker) has the plugin installed and enabled? It might be great to have a report/visualization based on indicators as well.

**Comment by poligarcia** [comment]
Hello @bishalkc ! The `ckan-dasboard` plugin seems to depend on the development version of CKAN.

As you know we're currently on CKAN 2.5.3, so we cannot use this plugin right now.
