### ISSUE TITLE
Views 

### ISSUE THREAD

**Issue by bishalkc** [datosgobar/portal-andino-theme#103]
If seems like you can delete the existing views but you cant create any new views. Also the Add Filter does not work under the Default VIEWS.
<img width="949" alt="screen shot 2017-09-12 at 11 54 05 pm" src="https://user-images.githubusercontent.com/5494719/30358963-b326a76a-9815-11e7-8b10-c41b6ce30e7b.png">
<img width="954" alt="screen shot 2017-09-12 at 11 53 49 pm" src="https://user-images.githubusercontent.com/5494719/30358962-b320447e-9815-11e7-999e-3cd0b91ad9ab.png">

**Comment by poligarcia** [comment]
this issue deplicates #80
