### ISSUE TITLE
Encontre un bug en andino

### ISSUE THREAD

**Issue by cristian04yamil** [datosgobar/portal-andino-theme#104]
Hola disculpen es posible levantar portal-andino-theme con xamp pasa que tengo  ya tengo alojados algunos sitios en mi xamp o alguna manera de poder levantar ambos sitios  sin tener
Desde ya muchas gracias .

**Comment by juanehernandez** [comment]
Estimado, por favor, explícanos puntualmente cual es el problema que estas teniendo.
Saludos
