### ISSUE TITLE
Formulario de carga y edición de un recurso

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino-theme#140]
Cuando cargo un archivo el label cambia a "url" y debería archivo

EL campo "Nombre del archivo" SOLO se debe mostrar cuando se cargo una url y NO cuando se cargo un archivo ya que el archivo ya tiene su propio nombre.

**Comment by poligarcia** [comment]
Este issue se cierra por ahora ya que se va a replantear la funcionalidad
