### ISSUE TITLE
En el formulario de metadatos del portal el campo "Fecha de lanzamiento" debería ser una componente date.

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino-theme#150]

**Comment by poligarcia** [comment]
Usar un componente similar al de `temporal` de un _dataset_:

![image](https://user-images.githubusercontent.com/1264073/36669208-dfc80a12-1ad2-11e8-861d-d8da1725d7b9.png)

La diferencia con éste sería que no tendríamos _from_/_to_ sino simplemente la fecha de lanzamiento. Debe permitir especificar la hora.

**Comment by juanehernandez** [comment]
No agreguemos el campo para la hora
