### ISSUE TITLE
Cambiar placeholder de "Responsable" y "Mantenedor"

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino-theme#153]
En el formulario de carga y edición de un dataset, el placeholder de:

"Responsable" debería ser "Ministerio de Modernización. Secretaría de Gestión e Innovación Pública. Subsecretaría de Innovación Pública y Gobierno Abierto."

"Mantenedor" debería ser "Ministerio de Modernización. Secretaría de Gestión e Innovación Pública. Subsecretaría de Innovación Pública y Gobierno Abierto. Dirección Nacional de Datos e Información Pública. Dirección de Datos Públicos"

Los inputs deberían tener el doble de alto(El input box tiene que ser mas grande para acomodar textos mas largos)

**Comment by poligarcia** [comment]
Luego de conversar con @juanehernandez quedamos en usar 2 líneas para responsable y 3 para mantenedor, ya que el texto default es muy largo
