### ISSUE TITLE
Fusión andino-datos.gob.ar: Vista de un recurso

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/portal-andino-theme#157]
El comportamiento de esta vista va a depender de si es un recurso "propio" o externo. 

SI es propio vamos a mostrar la vista con la seccion de previsualizacion tal cual es hoy.

En el caso de que sea externo vamos a mostrar la vista del recurso SIN la seccion de previsualizacion y vamos a agregar un botón debajo del descargar para poder consultar el recurso en el nodo origen

![previsualizacion_de_recurso-02](https://user-images.githubusercontent.com/1264073/36680742-6ac54d06-1af5-11e8-91e8-1965e237ffc7.png)

![previsualizacion_de_recurso-03](https://user-images.githubusercontent.com/1264073/36680747-6d3908de-1af5-11e8-938c-c7b554f3bad9.png)

**Comment by chdigiorno** [comment]
Definiciones derivadas de la reunión del 2-Mar-18:

* [ ] Si el _resource_ tiene el flag `datastore_active` en `false`, no mostrar el panel de "Previsualización".
* [ ] El botón de "Consultar en el portal de origen" debe aparecer cuando el _hostname_ del `accessUrl` del recurso no es igual al _hostname_ del sitio. Este último se debe obtener de la configuración de CKAN.
* [ ] El botón "Descargar" debe ser verde.
