### ISSUE TITLE
Datos en inglés en la tabla de metadatos de un recurso

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/portal-andino-theme#173]
**Contexto**

Algunos de los valores que aparecen en la tabla de metadatos de campos de un recurso aparecen con valores que no están destinados al usuario final, sino al usuario desarrollador de un data.json y/o que implementa aplicaciones basadas en el perfil de metadatos.

**Propuesta**

Implementar una lógica de visualización de metadatos de campos de un recurso que contemple las características de cada campo del perfil a nivel de "Field", en qué casos muestra *el valor tal como está en el data.json* y en qué casos *se usa un mapeo de "valor data.json" a "valor usuario"*, y que sea extensible para acomodar futuros casos.

- "Título de la columna" (_title_), "Descripción" (_description_), "Unidad de medida" (_units_), "Identificador" (_identifier_): se muestra el mismo valor que cargó el usuario, en el data.json y en la UI.
- "Tipo de dato" (_type_): se muestra en la UI el mismo valor que ve el usuario en el selector de "Tipo de dato" que ve en el formulario de Andino (Ej.: "Número (number)".
- "Tipo de dato especial" (_specialType_): se muestra en la UI el mismo valor que ve el usuario en el selector de "Tipo de dato especial" que ve en el formulario de Andino (Ej.: "Indice de tiempo").
- "Detalle de tipo especial" (_specialTypeDetail_): se muestra en la UI el mismo valor que ve el usuario en el selector de "Detalle de tipo de dato especial" que ve en el formulario de Andino (Ej.: "Anualmente", en el caso del selector asociado a "Tipo de dato especial" "Indice de tiempo" (_"time_index"_)). Cada 
"Tipo de dato especial" tiene asociado su propio selector con pares "clave, valor", en este caso es el mismo que se usa para _accrualPeriodicity_

**Comment by chdigiorno** [comment]
Cuando se guarda un recurso con una columna que contiene un tipo de dato (o se le agrega una al editarlo), se produce un error al entrar a su página.
Este error no se reproduce si no hay ningún tipo de dato.

**Comment by poligarcia** [comment]
No pude reproducirlo @chdigiorno !
