### ISSUE TITLE
error en la ejecucion

### ISSUE THREAD

**Issue by jloemig** [datosgobar/portal-andino-theme#29]
Hola. Instale el plugin del tema + dependencia y me da error 500. ckan 2.5
el ckan funciona bien cuando lo saco de las listas del plugin.
que puedo ver?

Log de instalacion..

Obtaining ckanext-gobar-theme from git+https://github.com/datosgobar/portal-andino-theme#egg=ckanext-gobar_theme
  Updating ./ckanext-gobar-theme clone
  Running setup.py (path:/usr/lib/ckan/default/src/ckanext-gobar-theme/setup.py) egg_info for package ckanext-gobar-theme
    
    warning: no files found matching '*.json' under directory 'ckanext/gobar_theme'
    warning: no files found matching '*.less' under directory 'ckanext/gobar_theme'
  Installing extra requirements: 'egg'
Installing collected packages: ckanext-gobar-theme
  Running setup.py develop for ckanext-gobar-theme
    
    warning: no files found matching '*.json' under directory 'ckanext/gobar_theme'
    warning: no files found matching '*.less' under directory 'ckanext/gobar_theme'
    Creating /usr/lib/ckan/default/lib/python2.7/site-packages/ckanext-gobar-theme.egg-link (link to .)
    ckanext-gobar-theme 0.0.1 is already the active version in easy-install.pth
    
    Installed /usr/lib/ckan/default/src/ckanext-gobar-theme
Successfully installed ckanext-gobar-theme

**Comment by iheredia** [comment]
Hola jloemig.

Primero que nada, necesito que me confirmes que estás intentando levantar el portal mediante una instalación local de ckan. En el [readme del repositorio](https://github.com/datosgobar/portal-andino-theme/blob/master/README.md) hay dos guias para la instalación del porta. Una mediante docker y una usando una instancia local de ckan. 

Por otro lado, necesito mas información acerca del error que te tira. 
¿Estás levantando ckan mediante paster? En caso de que asi sea, ¿Podés copiar el log del error que se loguea por consola? 

Saludos

**Comment by jloemig** [comment]
hola.
Te comento que somos gobierno en mardel.
Es una instalacion local de Ckan sobre debian 8.5,  te copio el log del apache (esta en el puerto 80 con un wsgi)

****** log *****
[Tue Apr 11 09:31:08.885321 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512] mod_wsgi (pid=3321): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
[Tue Apr 11 09:31:08.885413 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512] mod_wsgi (pid=3321): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Tue Apr 11 09:31:08.885460 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512] Traceback (most recent call last):
[Tue Apr 11 09:31:08.885492 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/etc/ckan/default/apache.wsgi", line 9, in <module>
[Tue Apr 11 09:31:08.885533 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     application = loadapp('config:%s' % config_filepath)
[Tue Apr 11 09:31:08.885549 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Tue Apr 11 09:31:08.885577 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     return loadobj(APP, uri, name=name, **kw)
[Tue Apr 11 09:31:08.885591 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Tue Apr 11 09:31:08.885611 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     return context.create()
[Tue Apr 11 09:31:08.885625 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Tue Apr 11 09:31:08.885646 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     return self.object_type.invoke(self)
[Tue Apr 11 09:31:08.885659 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Tue Apr 11 09:31:08.885679 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Tue Apr 11 09:31:08.885693 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
[Tue Apr 11 09:31:08.885715 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     val = callable(*args, **kw)
[Tue Apr 11 09:31:08.885735 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py", line 58, in make_app
[Tue Apr 11 09:31:08.885760 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     load_environment(conf, app_conf)
[Tue Apr 11 09:31:08.885774 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Tue Apr 11 09:31:08.885797 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     p.load_all(config)
[Tue Apr 11 09:31:08.885812 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Tue Apr 11 09:31:08.885834 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     load(*plugins)
[Tue Apr 11 09:31:08.885847 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 166, in load
[Tue Apr 11 09:31:08.885867 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     plugins_update()
[Tue Apr 11 09:31:08.885880 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]   File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 116, in plugins_update
[Tue Apr 11 09:31:08.885900 2017] [wsgi:error] [pid 3321:tid 140026808178432] [remote 127.0.0.1:512]     environment.update_config()

**** fin log ****
si le saco plugin del tema funca.
muchas gracias.
jose luis.

**Comment by iheredia** [comment]
Hola jose luis 
Gracias por el log. Te paso tres ideas que se me ocurren al ver esto:

- ¿Como instalaste el plugin? Al parecer lo que falla es la carga del plugin al entorno de ckan. ¿Lo instalaste via pip referenciando al repositorio? ([readme con documentación](https://github.com/datosgobar/portal-andino-theme/blob/master/docs/03_instalacion_tema_visual.md)). 

- Estas levantando ckan mediante un wsgi, no? ¿Probaste levantarlo directamente con paster sin wsgi solo para ver si levanta bien? Acá podriamos diferenciar si el problema está en el plugin mismo o en la interaccion del plugin con el wsgi.

- Algo que me olvidé de poner en el readme de instalación es que el plugin usa dos carpetas para guardar info relevante a la instancia (mea culpa si llega a ser por esto el error) . Estas carpetas son `/usr/lib/ckan/default/src/ckanext-gobar-theme/ckanext/gobar_theme/public/user_images/` y `/var/lib/ckan/theme_config/`. En esta ultima trata de escribir un json llamado `settings.json`. Acabo de subir un cambio al final del [readme de instalación](https://github.com/datosgobar/portal-andino-theme/blob/master/docs/03_instalacion_tema_visual.md) con esta parte

Suerte con el bug
Saludos

**Comment by jloemig** [comment]
Hola. Its alive. 
Levanto faltaba los. Dierectorios y el json. 
Ahora configuro y te digo. 
Muchas Gracias. 
Jose luis

**Comment by jloemig** [comment]
hola. Te comento que no puedo guardar ningun cambio en el tema, me parece que es un problema de permisos. podrias tirarme una soga?
muchas gracias.
jose luis.

**Comment by iheredia** [comment]
Hola jose 

Necesito un poco mas de info para ver cual es el problema ahora. Tiro preguntas:

- ¿El portal está levantando sin tirar errores? 
- ¿Estás pudiendo loguearte sin problemas? 
- ¿Ves el [link a la sección de configuración](https://raw.githubusercontent.com/datosgobar/portal-andino-theme/master/docs/assets/portal-andino-sec-config.png) en la home?
- ¿Si cambias alguna configuración, ves el cambio en el portal en el momento? 
- Todos los cambios de la confguración se escriben en el json que nombre anteriormente. ¿Ves cambios en este archivo? 
- ¿Está logueando algun error cuando se realizan cambios en el portal?

Saludos

**Comment by jloemig** [comment]
Hola Ignacio.
Ahi levanto, datos.osmgp.gov.ar estoy probando la configuracion, le di permisos a www-data en el directorio que agregaste. chusmealo.

Un abrazo.
Jose Luis.

**Comment by iheredia** [comment]
Hola jose

Bien, vamos por buen camino.

Recién recorrí varias secciones y el header alternó entre varias versiones ida y vuelta (con link a la seccion de Organizaciones y sin link) 
Vimos que estás usando un nginx y asumimos por lo tanto que estás usando un apache2. Dentro del archivo de conf que está en `/etc/apache2/sites-enable/el_nombre_de_la_config.conf` deberias modificar la seccion de `process` para que tenga 1 solo proceso y 15 o 20 threads. 
Esto se debe a que estamos haciendo un manejo particular de archivos en el portal y esto fuerza a que los archivos que levanta apache sean comunes para todas las ejecuciones para nuestro modulo de wsgi, lo cual implica usar un solo proceso. 

Con esto deberia resolverse. 
Si encontras algun otro problema obvio podes seguir consultandonos

Saludos

**Comment by jloemig** [comment]
Hola Igancio...
It worked like a charm. 
El tema es que ahora quiero crear usuarios para que mantengan las Organizaciones????
En el Doc dice que el Tema no contempla... como lo hago.

Muchas Gracias.
José Luis.

**Comment by iheredia** [comment]
Hola jose
Buenisimo que haya funcionado. 

Sobre el tema de usuarios, al día de hoy el portal no tiene soporte para multiples usuarios. Esto significa que el portal no tiene gestión de multiples usuarios, sino que solo está pensado para ser usado con el usuario admin que se crea durante la instalación de ckan.

Tenemos planificado agregar soporte para multiples usuarios con distintos roles y permisos, ya que es un pedido que tuvimos de varias areas, pero va a tardar como mínimo un par de semanas. Yo ya estuve empezando con el desarrollo de esta parte y si te interesa chusmear estuve bajando las tareas a issues dentro del [milestone de usuarios](https://github.com/datosgobar/portal-andino-theme/milestone/1) de este repositorio.

Si estas apurado con este tema, la única alternativa que puedo ofrecerte es agregar mas usuarios administradores del portal de la misma forma que se crea el usuario inicial. De esta forma habria varios usuarios y todos tendrian los mismos permisos de uso del sitio. 

Saludos

**Comment by jloemig** [comment]
Hola Ignacio.

Si es un par de semanas no hay problema.
Por ahora podemos esperar.
1. como hago para enterarme cuando actualices?
2. como actualzo yo cuanto este este nuevo feature?

Muchas Gracias.
Jose Luis.

**Comment by iheredia** [comment]
Hola jose.

Para el modo de instalación que usaste, basta con fijarte si hay nuevos commits dentro del branch master de este repositorio. Tratamos de poner solo los cambios estables en master, ya que quien lo instale de forma manual via pip va a estar descargando la versión de master. 

Para actualizar el portal, basta con actualizar el paquete de pip que instalaste. Si seguiste [este readme](https://github.com/datosgobar/portal-andino-theme/blob/master/docs/03_instalacion_tema_visual.md) entonces la carpeta de tu virtualenv es `/usr/lib/ckan/default` (sino, cambiá lo siguiente según corresponda). Dentro de esta carpeta hay otra llamada `src` que es donde se instalan todos los paquetes de pip. Entonces, para bajar una actualización deberias ejecutar: 
```
cd /usr/lib/ckan/default/src/ckanext-gobar-theme/
git pull
```
Y seguido a esto reiniciar la aplicación 

En cuanto a las demás consultas. Actualmente la descripción de la home y el texto de la sección de _"Acerca de"_ se muestran solo como texto plano. Y los únicos links que se pueden agregar al footer son los de redes sociales, mail de contacto y el link relacionado al logo que va en el footer. 
Podemos considerar agregar alguna de estas funcionalidades si es algo que les interesa a uds. 

Saludos

**Comment by jloemig** [comment]
Hola ignacio.
Quedo claro lo de la actualizacion. 
Algunos pedidos, diras tu si se hace por aca. 

1. El acerca de no podria soportar html o markdown? 
2. Estaria bueno un menu como datos. Gob. Ar
3. Para el footer 4 link customizables ok. 
4. Lo de usuarios y permisos sobre temas u org asi delegamos administracion somos pocos y hombre orquesta. 

Muchas gracias. 
Un abrazo. 
Jose luis

**Comment by iheredia** [comment]
Hola jose. 
Necesito que me aclares un poco mas a qué te referís en el punto 2. ¿De cual menú hablás?
Estamos evaluando el resto de los cambios
Saludos

**Comment by jloemig** [comment]
Hola Ignacio.

Punto 2 - Lo decia por el menu de Acerca de. Seria bueno poder poner algunas opciones con subopciones de link, para referenciar a otras paginas, personalizar le menu.

Otra cosa, "Que Pesado...", se podran poner paginas personlaizadas, sucede que por ejemplo hay cuestiones tipo Informes del BID que tienen contenido tipo Pagina html css. nos gustaria darle un formato de pagina con datos a algunas secciones, tipo Datos CABA.

PD. ayer en la Gerencia presente el trabajo y gane algunos Aplausos.. los queria compartir con ustedes.
Muchas Gracias.

Un abrazo.
Jose Luis.

**Comment by iheredia** [comment]
Hola Jose 

Que bueno que gustó la presentación frente a la gerencia :D felicitaciones
En breve te damos una respuesta sobre el menu y el resto de las ideas

Saludos

**Comment by jloemig** [comment]
Hola. Ignacio.

Queria saber algunas cosas:

1. como puedo poner negrita o cursiva en los detalles de los Dataset?
2. veo en datos.gov.ar que tienen Hipervinculos, link a paginas y mailto, como lo coloco?

Te comento que probe con html o markdown y no tuve exito.

Muchas Gracias.
José Luis.

**Comment by iheredia** [comment]
Hola José 

1. Al dia de hoy el texto de descripción de datasets y recursos solo soporta formato plano de texto. 

2. ¿Mailto y links a paginas dentro de la info del dataset? En el formulario de dataset hay un campo llamado "e-mail del responsable" que cuando está completo con un mail se agrega linkeado como mailto a la descripción del dataset. Lo mismo pasa con el campo "fuente" en el formulario de dataset.

3. No se a que te referis en este punto. ¿Una api? Ckan ya viene con una api integrada que podrian usar en caso de estar hablando de esto. Mas info acá: http://docs.ckan.org/en/latest/api/

4. Que lindo que está quedando el portal! Se lo paso a los demas del equipo para que lo vean y te pasamos comentarios :D 

Y no hay problema con que hagas consultas, todo lo contrario. En todo caso tenenos paciencia con el tiempo de respuesta 
Saludos!

**Comment by jloemig** [comment]
Hola Ignacio.

Respecto al punto:

2. Queria ver de tener paginas "sueltas" dentro de Ckan, con html y css.
3. Queremos publicar nuestros dataset, nuestros datos para que programadores armen sus apis desde ahi, pensé en Rest para esto?, además, quería ver si hay alguna guía de github, estimo que hay que abrir un proyecto?

Muchas Gracias.
Jose Luis.

**Comment by iheredia** [comment]
Hola José

Todavia no tenemos habilitada la generación de paginas independientes. 

Sigo sin entenderte del todo con el tema de la api. Ckan ya viene con una api integrada. De hecho, podrias empezar a usarla (por ej: http://datos.osmgp.gov.ar/api/3/action/package_list está funcionando dentro de tu portal). En el link que te pasé antes hay un listado de urls que la api tiene para consulta de datos. Podes pasarle eso a los programadores interesados en integrar los datos.

Saludos

**Comment by jloemig** [comment]
Hola Ignacio.

Disculpame si no expreso bien.
Tenemos la idea de publicar Datos via API que se puedan consumir desde una App y no sabemos como? (entendemos y hacemos Rest Soap ...)
Por eso te pedia tips.

Muchas Gracias.
Jose Luis.

**Comment by iheredia** [comment]
Hoa José

La metadata de los datasets publicados se pueden consultar desde la api nativa de ckan (el ultimo link que te pasé es un ejemplo de eso). 
Para consultar directamente los datos dentro de los archivos de los datasets hay que habilitar el plugin del datastore de ckan. Este plugin permite hacer lectura de datos directamente sobre los archivos subidos. Ejemplo dentro de datos.gob.ar: http://datos.gob.ar/api/3/action/datastore_search?resource_id=b0c58264-64f3-4ee8-a642-7208745f8fa7 Este de ejemplo json contiene datos del archivo del presupuesto de 2017 que se encuentra dentro del dataset de ejecución presupuestaria http://datos.gob.ar/dataset/ejecucion-presupuestaria-de-la-administracion-publica-nacional
Puede ser que no tengas instalado el plugin del datastore o que no esté corriendo. Cuando instalaste el portal tambien instalaste el plugin del datastore? Podes revisar los pasos de instalación acá por si te faltó algo: http://docs.ckan.org/en/latest/maintaining/datastore.html

En cuanto al mapa que les falta en la previsualización, no estoy del todo seguro que es lo que está pasando pero podemos empezar por estar seguros que el principal plugin del portal esté actualizado. 
Probá ejecutando 
```
cd /usr/lib/ckan/default/src/ckanext-gobar-theme/
git pull
```
La carpeta puede ser distinta, depende de donde hayas instalado el plugin. 
Si git te dice que estás al dia entonces avisame y lo revisamos. Si git te trae actualizaciones, reinicia el servidor y chequeá si el mapa sigue roto. En caso de que, lo seguimos debbugueando.

Saludos

**Comment by jloemig** [comment]
Hola Ignacio.

1.Te comento que actualice y sigue igual (resatrtr apache nginx) 
2. los datos los sube ok, pero mepa que algo con el Datastore esta mal.
3 cuando hago: 

# curl 127.0.0.1:8800
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /
on this server.<br />
</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at 127.0.0.1 Port 8800</address>
</body></html>
root@datos:/usr/lib/ckan/default/src/ckanext-gobar-theme# 
4.- cuando hago click en datastore, despues de haber cargado el recurso dice:
Error en la subida: An Error occurred while sending the job: 403 Client Error: Forbidden 

5. LÑos mapas no los muestra si el recurso no esta en el data store, por eso no funca.

Fijate y avisame.
muchas gracias.
jose luis.
