### ISSUE TITLE
Too many redirects al descargar recurso editado

### ISSUE THREAD

**Issue by lrromero** [datosgobar/portal-andino-theme#364]
Pasos para reproducir el bug:
1 - Crear un recurso y subir un archivo. (Es posible descargar el recurso en este paso.)
2 - Editar recurso y guardar cambios. (No hace falta hacer ningún cambio.)
3 - Descargar recurso.

Termina ocurriendo un error de too many redirects al intentar descargar el recurso

**Comment by poligarcia** [comment]
Workaround para este bug: Ante cualquier actualización del recurso, es necesario volver a adjuntar el archivo con los datos del recurso.
