### ISSUE TITLE
Mostrar version del plugin

### ISSUE THREAD

**Issue by iheredia** [datosgobar/portal-andino-theme#41]
(Ideado en proceso)
Estaría bueno poder saber desde la interfaz en que version está el plugin. 
Como al día de hoy no estamos haciendo releases con una lógica bien definida, tal vez lo mejor sea mostrar cual fue el último commit que tiene el repo.

**Comment by poligarcia** [comment]
Notas de la planning del Sprint 2: 
* Servir en formato JSON un conjunto de pares artefacto:versión que componen la instancia de Andino desde la API de CKAN
* Incluir la versión del portal datosgobar/portal-base#14
