### ISSUE TITLE
Accesibilidad

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino-theme#440]
Se deberán aplicar los estándares aprobados por Disposición N° 02/2014 de
la OFICINA NACIONAL DE TECNOLOGÍAS DE LA INFORMACIÓN de la
entonces SUBSECRETARÍA DE TECNOLOGÍAS DE GESTIÓN de la JEFATURA
DE GABINETE DE MINISTROS.

**Comment by lucaslavandeira** [comment]
Ver #482
