### ISSUE TITLE
Spike: Compatibilidad con Safari 7

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/portal-andino-theme#441]
Listar pantallas que tengan discrepancias de front end con versiones modernas de browsers

**Comment by chdigiorno** [comment]
A continuación, dejo las páginas navegadas y los resultados encontrados:


general: [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.css.map, line 0)
header + footer: ok
home: ok
/ingresar: ok
/dataset: ok
/borradores: ok
/dataset/new: ok
/dataset/edit/x: ok
/dataset/x/archivo/y: [Warning] Unexpected CSS token: : (bootstrap.css, line 3194), [Warning] Unexpected CSS token: : (bootstrap.css, line 5782), [Warning] Unexpected CSS token: : (bootstrap.css, line 5792), [Warning] Unexpected CSS token: : (leaflet.css, line 460), [Warning] Unexpected CSS token: : (:bundle:table.css;gobar_style.css, line 3093), [Warning] Unexpected CSS token: :(:bundle:table.css;gobar_style.css, line 5407)
[Warning] Unexpected CSS token: : (:bundle:table.css;gobar_style.css, line 5417)
[Warning] Unexpected CSS token: : (map.css, line 17)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.css.map, line 0)
/dataset/x/new_resource/y: problemas con Fichero y URL de acceso (custom forms, en /group/new sí funciona ver, hay que comparar el html). [Error] SyntaxError: Invalid character: '`' (anonymous function) (urls_and_icons.js, line 6197). Los botones de campos avanzados y extras no hacen nada. El botón de agregar otra columna no hace nada. El botón de borrar recurso no hace nada.
/organization/new: ok
/organizaciones: ok
/configurar/todos: ok
/group/new: ok
/series/api: ok
/series/api/series/alguna: no carga nada. message: "Can't find variable: URLSearchParams", [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.9be3ae19.js.map, line 0), 
     [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.css.map, line 0), [Error] Failed to load resource: the server responded with a status of 404   (Not Found) (bootstrap.css.map, line 0)
/dataset/resources/un_dataset: la posición de los recursos no cambia al tratar de reordenarlos
