### ISSUE TITLE
ckanext-security: contraseñas más seguras

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/portal-andino-theme#456]
Habiendo habilitado el plugin, se deben agregar a la UI mensajes que indiquen cómo deben estar conformadas las mismas.

**Comment by chdigiorno** [comment]
![image](https://user-images.githubusercontent.com/33754261/62387599-6b50e780-b531-11e9-9e65-bf4de18a1c29.png)
![image](https://user-images.githubusercontent.com/33754261/62387601-6db34180-b531-11e9-907a-a0fbe256f18e.png)
