### ISSUE TITLE
Imagen de Fondo - No impacta en la sección de Series

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino-theme#473]
En `/series` no toma la imagen que se sube desde la UI en los nodos.

![image](https://user-images.githubusercontent.com/33754261/64279856-48e22d80-cf26-11e9-8e63-b40898ea8976.png)

**Comment by pepeciavirella** [comment]
Resuelto en el PR #11 de ckanext-seriestiempoarexplorer
