### ISSUE TITLE
Accesibilidad

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/portal-andino-theme#482]
arreglar home de Andino , evaluar el resto de paginas publicadas.

**Comment by chdigiorno** [comment]
`/dataset`
Imagen (elemento "img") sin atributo "alt". Todas las imágenes deben contener una alternativa textual corta que transmita la misma información que la imagen.
Enlace cuyo único contenido es una imagen sin texto alternativo. Se debe indicar el propósito del enlace a través del atributo "alt" de la imagen.
Elemento de formulario sin etiqueta asociada ni atributo "title". Cuando el diseño no permite colocar un elemento "label", se debe usar el atributo "title" para identificar el propósito del control.
Elemento no semántico para marcar texto. Los elementos como "b", "font" e "i" no aportan contenido semántico al texto del documento.
Elemento de lista usado fuera de una lista (ol/ul). Los elementos "li" deben aparecer siempre dentro de una lista.
