### ISSUE TITLE
Dropdown se superpone

### ISSUE THREAD

**Issue by LorenaMelgarejo** [datosgobar/portal-andino-theme#509]
Al seleccionar el dropdown en las distintas secciones de la página , y realizar un scroll up  por la página, este se superpone al head 
Se utilizaron los navegadores Chrome y Microsoft Edge.

***El calendario overlapea el head.***
***Pasos:***
***1***-Disponer de Usuario Admin
***2***- Ingresar a la sección Metadatos del Portal
(Admin->Configuración->Metadatos del Portal)
***3***-hacer click en el campo  Fecha de lanzamiento.
***4***-scroll up the page.
![Calendario_superpone_gif](https://user-images.githubusercontent.com/22152649/66137655-c8215a80-e5d3-11e9-9bb0-2a0f84c3d310.gif)

.

**Comment by mfigueroa1** [comment]
Se verifica que el ticket ha sido resuelto correctamente
