### ISSUE TITLE
Evaluar reuso de las vistas de ckan-admin

### ISSUE THREAD

**Issue by iheredia** [datosgobar/portal-andino-theme#59]
La vista de administracion en /ckan-admin/trash permite eliminar definitivamente recursos que quedaron etiquetados como eliminados pero que aun asi siguen existiendo en la db. 
Evaluar si es una funcionalidad que queremos ofrecer al usuario o si la limpieza de la db se va a encarar por otro lado

**Comment by JuliColombo** [comment]
Resuelto acá https://github.com/datosgobar/portal-andino-theme/pull/75
