### ISSUE TITLE
Creación y administración de usuarios 

### ISSUE THREAD

**Issue by Wingman2** [datosgobar/portal-andino-theme#9]
Creación y administración de usuarios.

Usuarios pertenecientes a que organización y rol (Miembro, Editor,  Admin)

**Comment by iheredia** [comment]
¡Hola, @Wingman2!

Gracias por abrirnos el issue, valoramos un montón la ayuda.

Te contamos que las sugerencias que nos hacés son features que están presentes en la versión original de CKAN.

Nosotros, sin embargo, decidimos quitar estas funcionalidades, porque nos enfocamos en crear un portal para ser usado por organismos. Nos pareció bueno que la relevancia esté puesta en la entidad que gestiona el portal, más que en los usuarios individuales.  

Por este mismo motivo es que se ocultaron los links para registración y logueo de usuarios, y se descartaron todas las vistas y templates relacionados a usuarios y sus actividades.

Esperamos que nuestra aclaración te haya sido de ayuda y estamos abiertos a que nos dejes todas las sugerencias que creas necesarias.

Buena semana,
El equipo de Datos Argentina.

**Comment by tconticello** [comment]
Es posible mantener andino y a la vez habilitar dichas funcionalidades de manera de mantenernos a la par del resto de los ministerios?
Para nosotros es bastante importante poder tener el manejo de roles y usuarios dentro de cada organización.

Que recomiendan?

**Comment by iheredia** [comment]
Hola chicos. 

Despues de tener varios pedidos relacionados a este tema y pensarlo un poco, decidimos habilitar la posibilidad de tener distintos usuarios con distintos roles y permisos. 
No nos convence la forma nativa de ckan de asignar roles segun cada organizacion, asi que vamos a tratar de implementar una capa sobre esto para poder asignar roles directamente a cada usuario para todo el sitio. 

Yo principalmente voy a estar encarando el desarrollo, y estuve escribiendo lo que tengo en mente en forma de issues dentro del [milestone "Usuarios"](https://github.com/datosgobar/portal-andino-theme/milestone/1)

Cierro este issue. Si tienen alguna duda o consulta están invitados a crear otro issue o comentar en alguno de los existentes.

Saludos
